/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'customer' : IDL.Null,
  'labour' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Opt(IDL.Text),
  'role' : UserRole,
  'phone' : IDL.Opt(IDL.Text),
});
export const Labour = IDL.Record({
  'id' : IDL.Text,
  'principal' : IDL.Principal,
  'area' : IDL.Text,
  'name' : IDL.Text,
  'wage' : IDL.Nat,
  'createdTime' : IDL.Int,
  'available' : IDL.Bool,
  'skill' : IDL.Text,
  'rating' : IDL.Nat,
  'phone' : IDL.Text,
});
export const User = IDL.Record({
  'id' : IDL.Text,
  'principal' : IDL.Principal,
  'role' : UserRole,
  'createdTime' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getLaboursBySkillAndArea' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Labour)],
      ['query'],
    ),
  'getMyLabourProfile' : IDL.Func([], [IDL.Opt(Labour)], ['query']),
  'getUserInfo' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([UserRole], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setLabourAvailability' : IDL.Func([IDL.Bool], [], []),
  'updateLabourProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserRole = IDL.Variant({ 'customer' : IDL.Null, 'labour' : IDL.Null });
  const UserProfile = IDL.Record({
    'name' : IDL.Opt(IDL.Text),
    'role' : UserRole,
    'phone' : IDL.Opt(IDL.Text),
  });
  const Labour = IDL.Record({
    'id' : IDL.Text,
    'principal' : IDL.Principal,
    'area' : IDL.Text,
    'name' : IDL.Text,
    'wage' : IDL.Nat,
    'createdTime' : IDL.Int,
    'available' : IDL.Bool,
    'skill' : IDL.Text,
    'rating' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const User = IDL.Record({
    'id' : IDL.Text,
    'principal' : IDL.Principal,
    'role' : UserRole,
    'createdTime' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getLaboursBySkillAndArea' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Labour)],
        ['query'],
      ),
    'getMyLabourProfile' : IDL.Func([], [IDL.Opt(Labour)], ['query']),
    'getUserInfo' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([UserRole], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setLabourAvailability' : IDL.Func([IDL.Bool], [], []),
    'updateLabourProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };